import type { IconType } from 'react-icons';

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiDocumentText,
  HiOutlineInformationCircle,
  HiBellAlert,
  HiArrowLeft,
  HiOutlineCheckCircle,
  HiOutlineTrash,
  HiPencilSquare,
  HiPlayCircle,
  HiPhoto,
} from 'react-icons/hi2';

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiGameControllerDuotone,
  PiSignIn,
  PiSignOut,
  PiPenNib,
  PiFingerprint,
  PiBatteryMedium,
  PiShield,
  PiNetwork,
  PiCpu,
  PiGear,
  PiMaskHappy,
  PiBroom,
} from 'react-icons/pi';

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTailwindcss,
  SiPython,
  SiDjango,
  SiN8N,
  SiOpenai,
  SiCloudflare,
  SiTypescript,
  SiStripe,
  SiFirebase,
  SiBootstrap,
  SiShadcnui,
  SiChakraui,
  SiAntdesign,
  SiC,
  SiCplusplus,
  SiSqlite,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiGnubash,
  SiCelery,
  SiElixir,
  SiPhp,
  SiGooglesheets,
  SiGoogle,
  SiGit,
  SiDocker,
  SiSublimetext,
  SiAndroidstudio,
  SiExpo,
  SiVercel,
  SiNetlify,
  SiPostman,
  SiJira,
  SiPythonanywhere,
  SiTwilio,
  SiLaravel,
  SiFlask,
  SiJinja,
  SiNodedotjs,
  SiJupyter,
  SiVirustotal,
  SiGitlab,
  SiShopify,
  SiOpenstreetmap,
  SiGooglemaps,
  SiPytorch,
  SiHuggingface,
  SiOllama,
  SiLangchain,
  SiFastapi,
  SiAirtable,
  SiHubspot,
  SiZapier,
  SiPerplexity,
  SiSlack,
  SiAnthropic,
  SiAmazonwebservices,
  SiGooglecloud,
  SiDigitalocean,
} from 'react-icons/si';

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaCompass,
  FaGifts,
  FaMap,
} from 'react-icons/fa6';
import { DiVisualstudio } from 'react-icons/di';
import { FaCut, FaHandHolding, FaDatabase } from 'react-icons/fa';
import { GiBullseye, GiFishingHook } from 'react-icons/gi';

export const iconLibrary: Record<string, IconType> = {
  signin: PiSignIn,
  signout: PiSignOut,
  arrowUpRight: HiArrowUpRight,
  arrowLeft: HiArrowLeft,
  resume: HiDocumentText,
  arrowRight: HiArrowRight,
  map: FaMap,
  email: HiEnvelope,
  signature: PiFingerprint,
  battery: PiBatteryMedium,
  shield: PiShield,
  compass: FaCompass,
  gifts: FaGifts,
  cut: FaCut,
  clean: PiBroom,
  hook: GiFishingHook,
  masks: PiMaskHappy,
  network: PiNetwork,
  chip: PiCpu,
  settings: PiGear,
  alert: HiBellAlert,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  info: HiOutlineInformationCircle,
  hand: FaHandHolding,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  game: PiGameControllerDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  openstreetmap: SiOpenstreetmap,
  googlemaps: SiGooglemaps,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  react: SiReact,
  virustotal: SiVirustotal,
  tailwindcss: SiTailwindcss,
  python: SiPython,
  django: SiDjango,
  n8n: SiN8N,
  openai: SiOpenai,
  cloudflare: SiCloudflare,
  gitlab: SiGitlab,
  vscode: DiVisualstudio,
  google: SiGoogle,
  shopify: SiShopify,
  typescript: SiTypescript,
  stripe: SiStripe,
  firebase: SiFirebase,
  bootstrap: SiBootstrap,
  shadcnui: SiShadcnui,
  chakraui: SiChakraui,
  antdesign: SiAntdesign,
  c: SiC,
  cpp: SiCplusplus,
  bash: SiGnubash,
  elixir: SiElixir,
  php: SiPhp,
  celery: SiCelery,
  redis: SiRedis,
  sqlite: SiSqlite,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  laravel: SiLaravel,
  flask: SiFlask,
  jinja: SiJinja,
  nodejs: SiNodedotjs,
  jupyter: SiJupyter,
  googlesheets: SiGooglesheets,
  git: SiGit,
  docker: SiDocker,
  sublimetext: SiSublimetext,
  androidstudio: SiAndroidstudio,
  expo: SiExpo,
  vercel: SiVercel,
  netlify: SiNetlify,
  postman: SiPostman,
  jira: SiJira,
  pythonanywhere: SiPythonanywhere,
  twilio: SiTwilio,
  pen: PiPenNib,
  goal: GiBullseye,
  trash: HiOutlineTrash,
  edit: HiPencilSquare,
  playCircle: HiPlayCircle,
  photo: HiPhoto,
  sql: FaDatabase,
  pytorch: SiPytorch,
  huggingface: SiHuggingface,
  ollama: SiOllama,
  langchain: SiLangchain,
  fastapi: SiFastapi,
  airtable: SiAirtable,
  hubspot: SiHubspot,
  zapier: SiZapier,
  perplexity: SiPerplexity,
  slack: SiSlack,
  anthropic: SiAnthropic,
  aws: SiAmazonwebservices,
  gcp: SiGooglecloud,
  digitalocean: SiDigitalocean,
};


export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
